[refactor] kotlin 2.0 migration
Project-Unifest/unifest-android pull request #208
Opened 2024-07-07 12:48 UTC by easyhooon

refactor)
- Kotlin 2.0 migration 
  - Kotlin 과 Compose 의 버전 통합(버전 관리의 어려움 해결), Kotlin컴파일러 성능 향상  

feat)
- strong skipping mode 적용  
- stabilityConfigurationFile 추가 ->stability.config.conf 파일내에 클래스를 지정하여 해당 클래스가 stable 이 되도록 설정 
-> 다만 코드랩 과 다르게 java.time.LocalDate 클래스를 추가해줘도 해당 클래스가 stable 이 아닌 unstable 로 판단되는 문제가 존재
참고) 
https://developer.android.com/codelabs/jetpack-compose-performance?hl=ko#10

chore)
- Plugin const val 네이밍 컨벤션에 맞게 수정 AndroidApplication -> ANDROID_APPLICATION

아직 Kotlin 2.0 을 라이브러리들이 지원하지 않을 가능성이 있어, 기존의 앱의 동작들이 전부 정상적으로 실행되는지 확인해볼 필요가 있습니다.

2024-07-07 14:53 UTC, wjdtkdgns777 commented
수고하셨습니다 확인해보니까 홈화면에서 충돌나는게 있는데 요거는 제가 내일 수정해서 올려보겠습니다!!
감기 조심하세요 ㅠㅠ

2024-07-07 22:56 UTC, jisungbin commented on build-logic/src/main/kotlin/com/unifest/android/Compose.kt
> +                    "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=$rootDir/report/compose-metrics",
이번에 컴포즈가 코틀린 플러그인으로 합쳐지면서 컴포즈 전용 DSL이 추가됐습니다!

![image](https://github.com/Project-Unifest/unifest-android/assets/40740128/61e7ba61-e34f-4589-b779-4f9774b78300)

`ComposeCompilerGradlePluginExtension` 사용하시면 돼용

2024-07-07 22:58 UTC, jisungbin commented on gradle/libs.versions.toml
> +kotlinx-coroutines = "1.8.1"
`1.9.0-RC` 버전이 K2 최소 지원 버전입니다!

https://github.com/Kotlin/kotlinx.coroutines/releases/tag/1.9.0-RC

2024-07-07 23:00 UTC, jisungbin commented on gradle/libs.versions.toml
> +androidx-compose-compiler = "1.5.14"
컴포즈 컴파일러가 코틀린 표준 플러그인으로 추가된 이후부터는 이 버전은 더 이상 유효하지 않습니다!

2024-07-07 23:00 UTC, jisungbin approved these changes

2024-07-07 23:27 UTC, easyhooon commented on build-logic/src/main/kotlin/com/unifest/android/Compose.kt
> +                    "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=$rootDir/report/compose-metrics",
우오 훨씬 간단하게 변했네요 Android 공식문서에 아직 해당 부분이 업데이트가 되지않아서 억지로 끼워맞췄는데 역시 방법이 있었군요..!

2024-07-07 23:29 UTC, easyhooon commented on gradle/libs.versions.toml
> +kotlinx-coroutines = "1.8.1"
생각해보니 코루틴 버전도 올려줘야하는군요..! 제안해주신 버전은 1.8.1 인데 혹시 1.9.0-RC로 교체하라는 말로 이해하면 될까요? 이때부터 K2 를 지원하는것 같아서요!

2024-07-07 23:56 UTC, easyhooon commented on build-logic/src/main/kotlin/com/unifest/android/Compose.kt
> +                    "plugin:androidx.compose.compiler.plugins.kotlin:metricsDestination=$rootDir/report/compose-metrics",
앱 모듈에만 적어놓으면 안될것같고 compose 사용하는 convention plugin 에 모두 적용해야할 것 같은데 ComposeCompilerGradlePluginExtension 쓰는 방향으로 바꿔봐야겠슴니다!

2024-07-15 15:47 UTC, easyhooon commented
> 수고하셨습니다 확인해보니까 홈화면에서 충돌나는게 있는데 요거는 제가 내일 수정해서 올려보겠습니다!!
감기 조심하세요 ㅠㅠ

Calendar 라이브러리 측에서 아직 kotlin 2.0 지원을 하지 않은 것인지, 홈 화면 진입시 런타임에 터지는군요... kotlin 2.0 지원될 때 까지 일단 대기 한 후에, merge 하면 될 것 같습니다! 

```
Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.compose.foundation.gestures.snapping.SnapPositionInLayout" on path: DexPathList[[zip file "/data/app/~~ze2XOpyZn6KW8p6c2lzmyA==/com.unifest.android.dev-p2sQEHPnPHH_kv5y9hmSpw==/base.apk"],nativeLibraryDirectories=[/data/app/~~ze2XOpyZn6KW8p6c2lzmyA==/com.unifest.android.dev-p2sQEHPnPHH_kv5y9hmSpw==/lib/arm64, /data/app/~~ze2XOpyZn6KW8p6c2lzmyA==/com.unifest.android.dev-p2sQEHPnPHH_kv5y9hmSpw==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]] 
```

2024-07-16 23:32 UTC, jisungbin requested changes

2024-07-16 23:32 UTC, jisungbin commented on gradle/libs.versions.toml
> +kotlinx-coroutines = "1.9.0"
https://mvnrepository.com/artifact/org.jetbrains.kotlinx/kotlinx-coroutines-core/1.9.0-RC

1.9.0 버전은 없는 버전입니다~!
`-RC`까지 붙여야 해요!

2024-07-17 00:07 UTC, easyhooon commented on gradle/libs.versions.toml
> +kotlinx-coroutines = "1.9.0"
꼼꼼한 체크 감사합니다..!

2024-07-17 01:17 UTC, jisungbin approved these changes

2024-07-17 13:48 UTC, wjdtkdgns777 approved these changes

2024-07-30 13:38 UTC, easyhooon commented
> 제가 추측하기로는 Calendar 라이브러리 측에서 아직 kotlin 2.0 지원을 하지 않은 것인지, 홈 화면 진입시 런타임에 터지는군요... kotlin 2.0 지원될 때 까지 일단 대기 한 후에, merge 하면 될 것 같습니다! 

2.6.0-beta03 버전으로 업데이트하니 런타임 에러 발생하지 않는 것 확인했습니다. (KMP, Compose 1.7 지원 버전)

2024-07-30 14:39 UTC, wjdtkdgns777 approved these changes
LGTM 수고많으셨습니다!!!

2024-07-30 14:42 UTC, merged